---
name: Cursor Tunnel
version: "1.0.3"
slug: cursor-tunnel
description: Cursor CLI SSH Tunnel to access Home Assistant via Cursor IDE
url: https://github.com/legaetan/ha-cursor-tunnel
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
homeassistant_api: true
ports:
  22/tcp: 22
ports_description:
  22/tcp: SSH Server Port
map:
  - config
options:
  tunnel_name: haos
schema:
  tunnel_name: str?
