---
name: Cursor Tunnel
version: "1.0.9"
slug: cursor-tunnel
description: Cursor CLI SSH Tunnel to access Home Assistant via Cursor IDE
url: https://github.com/legaetan/ha-cursor-tunnel
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
homeassistant_api: true
map:
  - config
options:
  tunnel_name: haos
schema:
  tunnel_name: str?
